# Implementing an LLM-powered recommendation system

In [ ]:
import os
os.chdir('/desired/default/directory/path')

## Data Preprocessing

In [213]:
import pandas as pd

md = pd. read_csv('movies_metadata.csv')
md.head()

DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [214]:
import pandas as pd
import ast


# Convert string representation of dictionaries to actual dictionaries
md['genres'] = md['genres'].apply(ast.literal_eval)

# Transforming the 'genres' column
md['genres'] = md['genres'].apply(lambda x: [genre['name'] for genre in x])


md.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [215]:
# Calculate weighted rate (IMDb formula)
def calculate_weighted_rate(vote_average, vote_count, min_vote_count=10):
    return (vote_count / (vote_count + min_vote_count)) * vote_average + (min_vote_count / (vote_count + min_vote_count)) * 5.0

# Minimum vote count to prevent skewed results
vote_counts = md[md['vote_count'].notnull()]['vote_count'].astype('int')
min_vote_count = vote_counts.quantile(0.95)

# Create a new column 'weighted_rate'
md['weighted_rate'] = md.apply(lambda row: calculate_weighted_rate(row['vote_average'], row['vote_count'], min_vote_count), axis=1)
md.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,weighted_rate
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,7.499658
1,False,NaN,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,6.610362
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,5.262357
3,False,NaN,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,5.079915
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,5.199506

In [233]:
md = md.dropna()

In [234]:
md_final = md[['genres', 'title', 'overview', 'weighted_rate']].reset_index(drop=True)
md_final.head()

,genres,title,overview,weighted_rate
0,"[Adventure, Action, Thriller]",GoldenEye,James Bond must unmask the mysterious head of ...,6.173464
1,[Comedy],Friday,Craig and Smokey are two guys in Los Angeles h...,6.083421
2,"[Horror, Action, Thriller, Crime]",From Dusk Till Dawn,Seth Gecko and his younger brother Richard are...,6.503176
3,[Comedy],Blue in the Face,"Auggie runs a small tobacco shop in Brooklyn, ...",5.109091
4,"[Action, Adventure, Science Fiction, Family, F...",Mighty Morphin Power Rangers: The Movie,Power up with six incredible teens who out-man...,5.052129

In [235]:

# Create a new column by combining 'title', 'overview', and 'genre'
md_final['combined_info'] = md_final.apply(lambda row: f"Title: {row['title']}. Overview: {row['overview']} Genres: {', '.join(row['genres'])}. Rating: {row['weighted_rate']}", axis=1)
md_final['combined_info'][9]

'Title: Jurassic Park. Overview: A wealthy entrepreneur secretly creates a theme park featuring living dinosaurs drawn from prehistoric DNA. Before opening day, he invites a team of experts and his two eager grandchildren to experience the park and help calm anxious investors. However, the park is anything but amusing as the security systems go off-line and the dinosaurs escape. Genres: Adventure, Science Fiction. Rating: 7.39064935064935'

## Embeddings

In [236]:
# imports
import pandas as pd
import tiktoken
import os
import openai

openai.api_key = os.environ["OPENAI_API_KEY"]

from openai.embeddings_utils import get_embedding

# embedding model parameters
embedding_model = "text-embedding-ada-002"
embedding_encoding = "cl100k_base"  # this the encoding for text-embedding-ada-002
max_tokens = 8000  # the maximum for text-embedding-ada-002 is 8191

encoding = tiktoken.get_encoding(embedding_encoding)

# omit reviews that are too long to embed
md_final["n_tokens"] = md_final.combined_info.apply(lambda x: len(encoding.encode(x)))
md_final = md_final[md_final.n_tokens <= max_tokens]
len(md_final)

693

In [237]:
md_final.head()

,genres,title,overview,weighted_rate,combined_info,n_tokens
0,"[Adventure, Action, Thriller]",GoldenEye,James Bond must unmask the mysterious head of ...,6.173464,Title: GoldenEye. Overview: James Bond must un...,59
1,[Comedy],Friday,Craig and Smokey are two guys in Los Angeles h...,6.083421,Title: Friday. Overview: Craig and Smokey are ...,52
2,"[Horror, Action, Thriller, Crime]",From Dusk Till Dawn,Seth Gecko and his younger brother Richard are...,6.503176,Title: From Dusk Till Dawn. Overview: Seth Gec...,105
3,[Comedy],Blue in the Face,"Auggie runs a small tobacco shop in Brooklyn, ...",5.109091,Title: Blue in the Face. Overview: Auggie runs...,87
4,"[Action, Adventure, Science Fiction, Family, F...",Mighty Morphin Power Rangers: The Movie,Power up with six incredible teens who out-man...,5.052129,Title: Mighty Morphin Power Rangers: The Movie...,89

In [238]:
import openai
openai.api_key = os.environ["OPENAI_API_KEY"]

md_final["embedding"] = md_final.overview.apply(lambda x: get_embedding(x, engine=embedding_model))
md_final.head()

,genres,title,overview,weighted_rate,combined_info,n_tokens,embedding
0,"[Adventure, Action, Thriller]",GoldenEye,James Bond must unmask the mysterious head of ...,6.173464,Title: GoldenEye. Overview: James Bond must un...,59,"[-0.023236559703946114, -0.015966948121786118,..."
1,[Comedy],Friday,Craig and Smokey are two guys in Los Angeles h...,6.083421,Title: Friday. Overview: Craig and Smokey are ...,52,"[0.0015918031567707658, -0.010778157971799374,..."
2,"[Horror, Action, Thriller, Crime]",From Dusk Till Dawn,Seth Gecko and his younger brother Richard are...,6.503176,Title: From Dusk Till Dawn. Overview: Seth Gec...,105,"[-0.008583318442106247, -0.004688787739723921,..."
3,[Comedy],Blue in the Face,"Auggie runs a small tobacco shop in Brooklyn, ...",5.109091,Title: Blue in the Face. Overview: Auggie runs...,87,"[-0.020235184580087662, -0.012174611911177635,..."
4,"[Action, Adventure, Science Fiction, Family, F...",Mighty Morphin Power Rangers: The Movie,Power up with six incredible teens who out-man...,5.052129,Title: Mighty Morphin Power Rangers: The Movie...,89,"[-0.003904743120074272, -0.03925294429063797, ..."

In [239]:
md_final.rename(columns = {'embedding': 'vector'}, inplace = True)
md_final.rename(columns = {'combined_info': 'text'}, inplace = True)
md_final.to_pickle('movies.pkl')

## Start working with LLMs

In [240]:
from langchain.vectorstores import LanceDB

In [241]:
import pandas as pd

md = pd.read_pickle('movies.pkl')

md.head(2)

,genres,title,overview,weighted_rate,text,n_tokens,vector
0,"[Adventure, Action, Thriller]",GoldenEye,James Bond must unmask the mysterious head of ...,6.173464,Title: GoldenEye. Overview: James Bond must un...,59,"[-0.023236559703946114, -0.015966948121786118,..."
1,[Comedy],Friday,Craig and Smokey are two guys in Los Angeles h...,6.083421,Title: Friday. Overview: Craig and Smokey are ...,52,"[0.0015918031567707658, -0.010778157971799374,..."

In [247]:
md['text'][0]

'Title: GoldenEye. Overview: James Bond must unmask the mysterious head of the Janus Syndicate and prevent the leader from utilizing the GoldenEye weapons system to inflict devastating revenge on Britain. Genres: Adventure, Action, Thriller. Rating: 6.173464373464373'

In [242]:
import lancedb

uri = "data/sample-lancedb"
db = lancedb.connect(uri)
table = db.create_table("movies", md)

In [268]:
from langchain.document_loaders import UnstructuredHTMLLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import LanceDB
from langchain.llms import OpenAI
from langchain.chains import RetrievalQA
import os

key = os.environ["OPENAI_API_KEY"]

embeddings = OpenAIEmbeddings()

docsearch = LanceDB(connection = table, embedding = embeddings)

In [244]:
query = "I'm looking for an animated action movie. What could you suggest to me?"
docs = docsearch.similarity_search(query)
docs
# docs[0].page_content

[Document(page_content='Title: Hitman: Agent 47. Overview: An assassin teams up with a woman to help her find her father and uncover the mysteries of her ancestry. Genres: Action, Crime, Thriller. Rating: 5.365800865800866', metadata={'genres': array(['Action', 'Crime', 'Thriller'], dtype=object), 'title': 'Hitman: Agent 47', 'overview': 'An assassin teams up with a woman to help her find her father and uncover the mysteries of her ancestry.', 'weighted_rate': 5.365800865800866, 'n_tokens': 52, 'vector': array([-0.00566491, -0.01658553, -0.02255735, ..., -0.01242317,
        -0.01303058, -0.00709073], dtype=float32), '_distance': 0.42414575815200806}),
 Document(page_content='Title: A Good Day to Die Hard. Overview: Iconoclastic, take-no-prisoners cop John McClane, finds himself for the first time on foreign soil after traveling to Moscow to help his wayward son Jack - unaware that Jack is really a highly-trained CIA operative out to stop a nuclear weapons heist. With the Russian underworld in pursuit, and battling a countdown to war, the two McClanes discover that their opposing methods make them unstoppable heroes. Genres: Action, Thriller. Rating: 5.178041993422717', metadata={'genres': array(['Action', 'Thriller'], dtype=object), 'title': 'A Good Day to Die Hard', 'overview': 'Iconoclastic, take-no-prisoners cop John McClane, finds himself for the first time on foreign soil after traveling to Moscow to help his wayward son Jack - unaware that Jack is really a highly-trained CIA operative out to stop a nuclear weapons heist. With the Russian underworld in pursuit, and battling a countdown to war, the two McClanes discover that their opposing methods make them unstoppable heroes.', 'weighted_rate': 5.178041993422717, 'n_tokens': 111, 'vector': array([-0.01498934, -0.02228908, -0.01306022, ..., -0.00130485,
        -0.00664774, -0.0015233 ], dtype=float32), '_distance': 0.42637109756469727}),
 Document(page_content='Title: Transformers. Overview: Young teenager, Sam Witwicky becomes involved in the ancient struggle between two extraterrestrial factions of transforming robots â€“ the heroic Autobots and the evil Decepticons. Sam holds the clue to unimaginable power and the Decepticons will stop at nothing to retrieve it. Genres: Adventure, Science Fiction, Action. Rating: 6.447283923466021', metadata={'genres': array(['Adventure', 'Science Fiction', 'Action'], dtype=object), 'title': 'Transformers', 'overview': 'Young teenager, Sam Witwicky becomes involved in the ancient struggle between two extraterrestrial factions of transforming robots â€“ the heroic Autobots and the evil Decepticons. Sam holds the clue to unimaginable power and the Decepticons will stop at nothing to retrieve it.', 'weighted_rate': 6.447283923466021, 'n_tokens': 82, 'vector': array([-0.0085541 , -0.04153363, -0.00675735, ...,  0.01361886,
        -0.02674297, -0.00792264], dtype=float32), '_distance': 0.4277053773403168}),
 Document(page_content='Title: Ice Age: Dawn of the Dinosaurs. Overview: Times are changing for Manny the moody mammoth, Sid the motor mouthed sloth and Diego the crafty saber-toothed tiger. Life heats up for our heroes when they meet some new and none-too-friendly neighbors â€“ the mighty dinosaurs. Genres: Animation, Comedy, Family, Adventure. Rating: 6.264471780028944', metadata={'genres': array(['Animation', 'Comedy', 'Family', 'Adventure'], dtype=object), 'title': 'Ice Age: Dawn of the Dinosaurs', 'overview': 'Times are changing for Manny the moody mammoth, Sid the motor mouthed sloth and Diego the crafty saber-toothed tiger. Life heats up for our heroes when they meet some new and none-too-friendly neighbors â€“ the mighty dinosaurs.', 'weighted_rate': 6.264471780028944, 'n_tokens': 84, 'vector': array([-0.00151468, -0.00433621, -0.00944388, ..., -0.0069765 ,
        -0.00752185, -0.01455156], dtype=float32), '_distance': 0.4308919906616211})]

In [248]:
qa = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="stuff", retriever=docsearch.as_retriever(), return_source_documents=True)

query = "I'm looking for an animated action movie. What could you suggest to me?"
result = qa({"query": query})
result['result']

' I would suggest Transformers. It is an animated action movie with genres of Adventure, Science Fiction, and Action, and a rating of 6.447283923466021.'

In [252]:
result['source_documents'][2]

Document(page_content='Title: Transformers. Overview: Young teenager, Sam Witwicky becomes involved in the ancient struggle between two extraterrestrial factions of transforming robots â€“ the heroic Autobots and the evil Decepticons. Sam holds the clue to unimaginable power and the Decepticons will stop at nothing to retrieve it. Genres: Adventure, Science Fiction, Action. Rating: 6.447283923466021', metadata={'genres': array(['Adventure', 'Science Fiction', 'Action'], dtype=object), 'title': 'Transformers', 'overview': 'Young teenager, Sam Witwicky becomes involved in the ancient struggle between two extraterrestrial factions of transforming robots â€“ the heroic Autobots and the evil Decepticons. Sam holds the clue to unimaginable power and the Decepticons will stop at nothing to retrieve it.', 'weighted_rate': 6.447283923466021, 'n_tokens': 82, 'vector': array([-0.0085541 , -0.04153363, -0.00675735, ...,  0.01361886,
       -0.02674297, -0.00792264], dtype=float32), '_distance': 0.4277053773403168})

In [254]:
df_filtered = md[md['genres'].apply(lambda x: 'Comedy' in x)]
qa = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="stuff", 
    retriever=docsearch.as_retriever(search_kwargs={'data': df_filtered}), return_source_documents=True)

query = "I'm looking for a movie with animals and an adventurous plot."
result = qa({"query": query})
result

{'query': "I'm looking for a movie with animals and an adventurous plot.",
 'result': " Ice Age might be a good choice for you. It's an animated, comedy, family, and adventure movie about a mismatched trio of prehistoric critters who are facing an impending ice age. The rating for Ice Age is 6.892297174111213.",
 'source_documents': [Document(page_content='Title: Cats & Dogs 2 : The Revenge of Kitty Galore. Overview: The ongoing war between the canine and feline species is put on hold when they join forces to thwart a rogue cat spy with her own sinister plans for conquest. Genres: Comedy, Family. Rating: 4.978057553956835', metadata={'genres': array(['Comedy', 'Family'], dtype=object), 'title': 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'overview': 'The ongoing war between the canine and feline species is put on hold when they join forces to thwart a rogue cat spy with her own sinister plans for conquest.', 'weighted_rate': 4.978057553956835, 'n_tokens': 66, 'vector': array([-0.00937352, -0.02231603, -0.00789624, ...,  0.00333204,
          0.00743868, -0.02941481], dtype=float32), '_distance': 0.3443989157676697}),
  Document(page_content="Title: The Curse of the Were-Rabbit. Overview: Cheese-loving eccentric Wallace and his cunning canine pal, Gromit, investigate a mystery in Nick Park's animated adventure, in which the lovable inventor and his intrepid pup run a business ridding the town of garden pests. Using only humane methods that turn their home into a halfway house for evicted vermin, the pair stumble upon a mystery involving a voracious vegetarian monster that threatens to ruin the annual veggie-growing contest. Genres: Adventure, Animation, Comedy, Family. Rating: 6.085923217550274", metadata={'genres': array(['Adventure', 'Animation', 'Comedy', 'Family'], dtype=object), 'title': 'The Curse of the Were-Rabbit', 'overview': "Cheese-loving eccentric Wallace and his cunning canine pal, Gromit, investigate a mystery in Nick Park's animated adventure, in which the lovable inventor and his intrepid pup run a business ridding the town of garden pests. Using only humane methods that turn their home into a halfway house for evicted vermin, the pair stumble upon a mystery involving a voracious vegetarian monster that threatens to ruin the annual veggie-growing contest.", 'weighted_rate': 6.085923217550274, 'n_tokens': 120, 'vector': array([ 0.00895139, -0.01685125, -0.01092802, ...,  0.01110772,
         -0.00367373, -0.02710043], dtype=float32), '_distance': 0.36180025339126587}),
  Document(page_content='Title: Ice Age. Overview: With the impending ice age almost upon them, a mismatched trio of prehistoric critters â€“ Manny the woolly mammoth, Diego the saber-toothed tiger and Sid the giant sloth â€“ find an orphaned infant and decide to return it to its human parents. Along the way, the unlikely allies become friends but, when enemies attack, their quest takes on far nobler aims. Genres: Animation, Comedy, Family, Adventure. Rating: 6.892297174111213', metadata={'genres': array(['Animation', 'Comedy', 'Family', 'Adventure'], dtype=object), 'title': 'Ice Age', 'overview': 'With the impending ice age almost upon them, a mismatched trio of prehistoric critters â€“ Manny the woolly mammoth, Diego the saber-toothed tiger and Sid the giant sloth â€“ find an orphaned infant and decide to return it to its human parents. Along the way, the unlikely allies become friends but, when enemies attack, their quest takes on far nobler aims.', 'weighted_rate': 6.892297174111213, 'n_tokens': 107, 'vector': array([-0.0021034 , -0.02123785, -0.01054541, ...,  0.00296882,
         -0.00765846, -0.02345653], dtype=float32), '_distance': 0.3627752959728241}),
  Document(page_content="Title: Marley & Me. Overview: A newly married couple who, in the process of starting a family, learn many of life's important lessons from their trouble-loving retriever, Marley. Packed with plenty of laughs to lighten the load, the film explores the highs and lows of marriage, maturity and confronting one's own mortality, as seen through the lens of family life with a dog. Genres: Comedy, Family. Rating: 6.44841182913472", metadata={'genres': array(['Comedy', 'Family'], dtype=object), 'title': 'Marley & Me', 'overview': "A newly married couple who, in the process of starting a family, learn many of life's important lessons from their trouble-loving retriever, Marley. Packed with plenty of laughs to lighten the load, the film explores the highs and lows of marriage, maturity and confronting one's own mortality, as seen through the lens of family life with a dog.", 'weighted_rate': 6.44841182913472, 'n_tokens': 98, 'vector': array([-0.00143638, -0.02463391, -0.01529539, ..., -0.00575853,
         -0.01565957, -0.02555735], dtype=float32), '_distance': 0.3638021945953369})]}

In [34]:
qa = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="stuff", 
    retriever=docsearch.as_retriever(search_kwargs={'filter': {'adult':'False'}}), return_source_documents=True)

query = "I'm looking for a movie with animals and an adventurous plot."
result = qa({"query": query})
result

{'query': "I'm looking for a movie with animals and an adventurous plot.",
 'result': ' Wallace and Gromit: The Curse of the Were-Rabbit, Ice Age, and Marley & Me all feature animals in adventurous plots.',
 'source_documents': [Document(page_content='The ongoing war between the canine and feline species is put on hold when they join forces to thwart a rogue cat spy with her own sinister plans for conquest.', metadata={'adult': 'False', 'genres': array(['Comedy', 'Family'], dtype=object), 'title': 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'weighted_rate': 4.978057553956835, 'n_tokens': 32, 'vector': array([-0.00937352, -0.02231603, -0.00789624, ...,  0.00333204,
          0.00743868, -0.02941481], dtype=float32), '_distance': 0.3447684347629547}),
  Document(page_content="Cheese-loving eccentric Wallace and his cunning canine pal, Gromit, investigate a mystery in Nick Park's animated adventure, in which the lovable inventor and his intrepid pup run a business ridding the town of garden pests. Using only humane methods that turn their home into a halfway house for evicted vermin, the pair stumble upon a mystery involving a voracious vegetarian monster that threatens to ruin the annual veggie-growing contest.", metadata={'adult': 'False', 'genres': array(['Adventure', 'Animation', 'Comedy', 'Family'], dtype=object), 'title': 'The Curse of the Were-Rabbit', 'weighted_rate': 6.085923217550274, 'n_tokens': 88, 'vector': array([ 0.00895139, -0.01685125, -0.01092802, ...,  0.01110772,
         -0.00367373, -0.02710043], dtype=float32), '_distance': 0.36215221881866455}),
  Document(page_content='With the impending ice age almost upon them, a mismatched trio of prehistoric critters â€“ Manny the woolly mammoth, Diego the saber-toothed tiger and Sid the giant sloth â€“ find an orphaned infant and decide to return it to its human parents. Along the way, the unlikely allies become friends but, when enemies attack, their quest takes on far nobler aims.', metadata={'adult': 'False', 'genres': array(['Animation', 'Comedy', 'Family', 'Adventure'], dtype=object), 'title': 'Ice Age', 'weighted_rate': 6.892297174111213, 'n_tokens': 79, 'vector': array([-0.0021034 , -0.02123785, -0.01054541, ...,  0.00296882,
         -0.00765846, -0.02345653], dtype=float32), '_distance': 0.3630030155181885}),
  Document(page_content="A newly married couple who, in the process of starting a family, learn many of life's important lessons from their trouble-loving retriever, Marley. Packed with plenty of laughs to lighten the load, the film explores the highs and lows of marriage, maturity and confronting one's own mortality, as seen through the lens of family life with a dog.", metadata={'adult': 'False', 'genres': array(['Comedy', 'Family'], dtype=object), 'title': 'Marley & Me', 'weighted_rate': 6.44841182913472, 'n_tokens': 72, 'vector': array([-0.00143638, -0.02463391, -0.01529539, ..., -0.00575853,
         -0.01565957, -0.02555735], dtype=float32), '_distance': 0.36415261030197144})]}

In [28]:
result['output']

'Here are some action movies that you might enjoy:\n\n1. [REC]Â² - The action continues from [REC], with a medical officer and a SWAT team sent into a sealed-off apartment to control the situation. It is a thriller/horror movie.\n\n2. The Boondock Saints - Twin brothers Conner and Murphy take swift retribution into their own hands to rid Boston of criminals. It is an action/thriller/crime movie.\n\n3. The Gamers - Four clueless players are sent on a quest to rescue a princess and must navigate dangerous forests, ancient ruins, and more. It is an action/comedy/thriller/foreign movie.\n\n4. Atlas Shrugged Part III: Who is John Galt? - In a collapsing economy, one man has the answer while others try to control or save him. It is a drama/science fiction/mystery movie.\n\nPlease note that these recommendations are based on the genre "action" and may vary in terms of availability and personal preferences.'

In [45]:
from langchain.agents.openai_functions_agent.base import OpenAIFunctionsAgent
from langchain.schema.messages import SystemMessage
from langchain.prompts import MessagesPlaceholder
from langchain.agents.openai_functions_agent.agent_token_buffer_memory import AgentTokenBufferMemory



system_message = SystemMessage(
        content=(
            "Do your best to answer the questions. "
            "if there are more than one argument for the single-input tool, reason step by step and treat them as single input. "
            "relevant information, only if neccessary"
        )
)

# This is needed for both the memory and the prompt
memory_key = "history"

memory = AgentTokenBufferMemory(memory_key=memory_key, llm=llm)

prompt = OpenAIFunctionsAgent.create_prompt(
        system_message=system_message,
        extra_prompt_messages=[MessagesPlaceholder(variable_name=memory_key)]
    )
agent_executor = create_conversational_retrieval_agent(llm=llm, tools=tools, prompt = prompt, verbose=True)

result = agent_executor({"input": "I liked a lot kung fu panda 1 and 2. Could you suggest me some similar movies?"})
result

> Entering new AgentExecutor chain...

Invoking: `movies` with `{'title': 'Kung Fu Panda'}`


[Document(page_content='When the Valley of Peace is threatened, lazy Po the panda discovers his destiny as the "chosen one" and trains to become a kung fu hero, but transforming the unsleek slacker into a brave warrior won\'t be easy. It\'s up to Master Shifu and the Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- to give it a try.', metadata={'adult': 'False', 'genres': array(['Adventure', 'Animation', 'Family', 'Comedy'], dtype=object), 'title': 'Kung Fu Panda', 'weighted_rate': 6.675006821282402, 'n_tokens': 79, 'vector': array([-0.00345203, -0.03163854,  0.00223724, ...,  0.00216131,
        0.00014942, -0.01268781], dtype=float32), '_distance': 0.20448510348796844}), Document(page_content='Po is now living his dream as The Dragon Warrior, protecting the Valley of Peace alongside his friends and fellow kung fu masters, The Furious Five - Tigress, Crane, Mantis, Viper and Monkey. But Poâ€™s new life of awesomeness is threatened by the emergence of a formidable villain, who plans to use a secret, unstoppable weapon to conquer China and destroy kung fu. It is up to Po and The Furious Five to journey across China to face this threat and vanquish it. But how can Po stop a weapon that can stop kung fu? He must look to his past and uncover the secrets of his mysterious origins; only then will he be able to unlock the strength he needs to succeed.', metadata={'adult': 'False', 'genres': array(['Animation', 'Family'], dtype=object), 'title': 'Kung Fu Panda 2', 'weighted_rate': 6.387240356083087, 'n_tokens': 148, 'vector': array([ 0.00179355, -0.02989138, -0.00742091, ..., -0.00236976,
       -0.00606398, -0.00903104], dtype=float32), '_distance': 0.24536560475826263}), Document(page_content='Asian Hawk (Jackie Chan) leads a mercenary team to recover several lost artifacts from the Old Summer Palace, the bronze heads of the 12 Chinese Zodiac animals which were sacked by the French and British armies from the imperial Summer Palace in Beijing in 1860. Assisted by a Chinese student & a Parisian lady, Hawk stops at nothing to accomplish the mission.', metadata={'adult': 'False', 'genres': array(['Action', 'Adventure'], dtype=object), 'title': 'Chinese Zodiac', 'weighted_rate': 5.380000000000001, 'n_tokens': 75, 'vector': array([-0.00208469, -0.00418268, -0.00532402, ..., -0.00832544,
        0.00562683, -0.01166626], dtype=float32), '_distance': 0.34648555517196655}), Document(page_content='Into the world of the Emperor Penguins, who find their soul mates through song, a penguin is born who cannot sing. But he can tap dance something fierce!', metadata={'adult': 'False', 'genres': array(['Animation', 'Comedy'], dtype=object), 'title': 'Happy Feet', 'weighted_rate': 5.69344262295082, 'n_tokens': 33, 'vector': array([-8.04522933e-05, -3.50862592e-02,  1.42071005e-02, ...,
       -2.17840052e-03,  2.18484085e-03, -3.50089744e-02], dtype=float32), '_distance': 0.34831809997558594})]Based on your liking for Kung Fu Panda 1 and 2, I would suggest the following similar movies:

1. Chinese Zodiac: This action-adventure film follows Asian Hawk, played by Jackie Chan, as he leads a mercenary team to recover lost artifacts. The movie combines action and adventure elements similar to Kung Fu Panda.

2. Happy Feet: This animated comedy film tells the story of a penguin who can't sing but can tap dance. While it may not have the martial arts theme, it shares the comedic and family-friendly elements found in Kung Fu Panda.

These movies offer a mix of adventure, animation, and comedy, which are similar to the themes present in Kung Fu Panda.

> Finished chain.

{'input': 'I liked a lot kung fu panda 1 and 2. Could you suggest me some similar movies?',
 'chat_history': [HumanMessage(content='I liked a lot kung fu panda 1 and 2. Could you suggest me some similar movies?', additional_kwargs={}, example=False),
  AIMessage(content='', additional_kwargs={'function_call': {'name': 'movies', 'arguments': '{\n  "title": "Kung Fu Panda"\n}'}}, example=False),
  FunctionMessage(content='[Document(page_content=\'When the Valley of Peace is threatened, lazy Po the panda discovers his destiny as the "chosen one" and trains to become a kung fu hero, but transforming the unsleek slacker into a brave warrior won\\\'t be easy. It\\\'s up to Master Shifu and the Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- to give it a try.\', metadata={\'adult\': \'False\', \'genres\': array([\'Adventure\', \'Animation\', \'Family\', \'Comedy\'], dtype=object), \'title\': \'Kung Fu Panda\', \'weighted_rate\': 6.675006821282402, \'n_tokens\': 79, \'vector\': array([-0.00345203, -0.03163854,  0.00223724, ...,  0.00216131,\n        0.00014942, -0.01268781], dtype=float32), \'_distance\': 0.20448510348796844}), Document(page_content=\'Po is now living his dream as The Dragon Warrior, protecting the Valley of Peace alongside his friends and fellow kung fu masters, The Furious Five - Tigress, Crane, Mantis, Viper and Monkey. But Poâ€™s new life of awesomeness is threatened by the emergence of a formidable villain, who plans to use a secret, unstoppable weapon to conquer China and destroy kung fu. It is up to Po and The Furious Five to journey across China to face this threat and vanquish it. But how can Po stop a weapon that can stop kung fu? He must look to his past and uncover the secrets of his mysterious origins; only then will he be able to unlock the strength he needs to succeed.\', metadata={\'adult\': \'False\', \'genres\': array([\'Animation\', \'Family\'], dtype=object), \'title\': \'Kung Fu Panda 2\', \'weighted_rate\': 6.387240356083087, \'n_tokens\': 148, \'vector\': array([ 0.00179355, -0.02989138, -0.00742091, ..., -0.00236976,\n       -0.00606398, -0.00903104], dtype=float32), \'_distance\': 0.24536560475826263}), Document(page_content=\'Asian Hawk (Jackie Chan) leads a mercenary team to recover several lost artifacts from the Old Summer Palace, the bronze heads of the 12 Chinese Zodiac animals which were sacked by the French and British armies from the imperial Summer Palace in Beijing in 1860. Assisted by a Chinese student & a Parisian lady, Hawk stops at nothing to accomplish the mission.\', metadata={\'adult\': \'False\', \'genres\': array([\'Action\', \'Adventure\'], dtype=object), \'title\': \'Chinese Zodiac\', \'weighted_rate\': 5.380000000000001, \'n_tokens\': 75, \'vector\': array([-0.00208469, -0.00418268, -0.00532402, ..., -0.00832544,\n        0.00562683, -0.01166626], dtype=float32), \'_distance\': 0.34648555517196655}), Document(page_content=\'Into the world of the Emperor Penguins, who find their soul mates through song, a penguin is born who cannot sing. But he can tap dance something fierce!\', metadata={\'adult\': \'False\', \'genres\': array([\'Animation\', \'Comedy\'], dtype=object), \'title\': \'Happy Feet\', \'weighted_rate\': 5.69344262295082, \'n_tokens\': 33, \'vector\': array([-8.04522933e-05, -3.50862592e-02,  1.42071005e-02, ...,\n       -2.17840052e-03,  2.18484085e-03, -3.50089744e-02], dtype=float32), \'_distance\': 0.34831809997558594})]', additional_kwargs={}, name='movies'),
  AIMessage(content="Based on your liking for Kung Fu Panda 1 and 2, I would suggest the following similar movies:\n\n1. Chinese Zodiac: This action-adventure film follows Asian Hawk, played by Jackie Chan, as he leads a mercenary team to recover lost artifacts. The movie combines action and adventure elements similar to Kung Fu Panda.\n\n2. Happy Feet: This animated comedy film tells the story of a penguin who can't sing but can tap dance. While it may not have the martial arts theme, it shares the comedic and family-friendly elements found in Kung Fu Panda.\n\nThese movies offer a mix of adventure, animation, and comedy, which are similar to the themes present in Kung Fu Panda.", additional_kwargs={}, example=False)],
 'output': "Based on your liking for Kung Fu Panda 1 and 2, I would suggest the following similar movies:\n\n1. Chinese Zodiac: This action-adventure film follows Asian Hawk, played by Jackie Chan, as he leads a mercenary team to recover lost artifacts. The movie combines action and adventure elements similar to Kung Fu Panda.\n\n2. Happy Feet: This animated comedy film tells the story of a penguin who can't sing but can tap dance. While it may not have the martial arts theme, it shares the comedic and family-friendly elements found in Kung Fu Panda.\n\nThese movies offer a mix of adventure, animation, and comedy, which are similar to the themes present in Kung Fu Panda.",
 'intermediate_steps': [(_FunctionsAgentAction(tool='movies', tool_input={'title': 'Kung Fu Panda'}, log="\nInvoking: `movies` with `{'title': 'Kung Fu Panda'}`\n\n\n", message_log=[AIMessage(content='', additional_kwargs={'function_call': {'name': 'movies', 'arguments': '{\n  "title": "Kung Fu Panda"\n}'}}, example=False)]),
   [Document(page_content='When the Valley of Peace is threatened, lazy Po the panda discovers his destiny as the "chosen one" and trains to become a kung fu hero, but transforming the unsleek slacker into a brave warrior won\'t be easy. It\'s up to Master Shifu and the Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- to give it a try.', metadata={'adult': 'False', 'genres': array(['Adventure', 'Animation', 'Family', 'Comedy'], dtype=object), 'title': 'Kung Fu Panda', 'weighted_rate': 6.675006821282402, 'n_tokens': 79, 'vector': array([-0.00345203, -0.03163854,  0.00223724, ...,  0.00216131,
            0.00014942, -0.01268781], dtype=float32), '_distance': 0.20448510348796844}),
    Document(page_content='Po is now living his dream as The Dragon Warrior, protecting the Valley of Peace alongside his friends and fellow kung fu masters, The Furious Five - Tigress, Crane, Mantis, Viper and Monkey. But Poâ€™s new life of awesomeness is threatened by the emergence of a formidable villain, who plans to use a secret, unstoppable weapon to conquer China and destroy kung fu. It is up to Po and The Furious Five to journey across China to face this threat and vanquish it. But how can Po stop a weapon that can stop kung fu? He must look to his past and uncover the secrets of his mysterious origins; only then will he be able to unlock the strength he needs to succeed.', metadata={'adult': 'False', 'genres': array(['Animation', 'Family'], dtype=object), 'title': 'Kung Fu Panda 2', 'weighted_rate': 6.387240356083087, 'n_tokens': 148, 'vector': array([ 0.00179355, -0.02989138, -0.00742091, ..., -0.00236976,
           -0.00606398, -0.00903104], dtype=float32), '_distance': 0.24536560475826263}),
    Document(page_content='Asian Hawk (Jackie Chan) leads a mercenary team to recover several lost artifacts from the Old Summer Palace, the bronze heads of the 12 Chinese Zodiac animals which were sacked by the French and British armies from the imperial Summer Palace in Beijing in 1860. Assisted by a Chinese student & a Parisian lady, Hawk stops at nothing to accomplish the mission.', metadata={'adult': 'False', 'genres': array(['Action', 'Adventure'], dtype=object), 'title': 'Chinese Zodiac', 'weighted_rate': 5.380000000000001, 'n_tokens': 75, 'vector': array([-0.00208469, -0.00418268, -0.00532402, ..., -0.00832544,
            0.00562683, -0.01166626], dtype=float32), '_distance': 0.34648555517196655}),
    Document(page_content='Into the world of the Emperor Penguins, who find their soul mates through song, a penguin is born who cannot sing. But he can tap dance something fierce!', metadata={'adult': 'False', 'genres': array(['Animation', 'Comedy'], dtype=object), 'title': 'Happy Feet', 'weighted_rate': 5.69344262295082, 'n_tokens': 33, 'vector': array([-8.04522933e-05, -3.50862592e-02,  1.42071005e-02, ...,
           -2.17840052e-03,  2.18484085e-03, -3.50089744e-02], dtype=float32), '_distance': 0.34831809997558594})])]}

## Prompt engineering

In [255]:
from langchain.prompts import PromptTemplate

template = """You are a movie recommender system that help users to find movies that match their preferences. 
Use the following pieces of context to answer the question at the end. 
For each question, suggest three movies, with a short description of the plot and the reason why the user migth like it.
If you don't know the answer, just say that you don't know, don't try to make up an answer.

{context}

Question: {question}
Your response:"""


PROMPT = PromptTemplate(
    template=template, input_variables=["context", "question"])

chain_type_kwargs = {"prompt": PROMPT}
qa = RetrievalQA.from_chain_type(llm=OpenAI(), 
    chain_type="stuff", 
    retriever=docsearch.as_retriever(),
    return_source_documents=True, 
    chain_type_kwargs=chain_type_kwargs)

query = "I'm looking for a funny action movie, any suggestion?"
result = qa({'query':query})
print(result['result'])

1. A Good Day to Die Hard: An action-packed comedy directed by John Moore, this movie follows Iconoclastic, take-no-prisoners cop John McClane as he travels to Moscow to help his wayward son Jack. With the Russian underworld in pursuit, and battling a countdown to war, the two McClanes discover that their opposing methods make them unstoppable heroes.
2. The Hidden: An alien is on the run in America and uses the bodies of anyone in its way as a hiding place. With lots of innocent people dying in the chase, this action-packed horror movie is sure to keep you laughing.
3. District B13: Set in the ghettos of Paris in 2010, this action-packed science fiction movie follows an undercover cop and ex-thug as they try to infiltrate a gang in order to defuse a neutron bomb. A thrilling comedy that will keep you laughing.

In [256]:
from langchain.prompts import PromptTemplate

template_prefix = """You are a movie recommender system that help users to find movies that match their preferences. 
Use the following pieces of context to answer the question at the end. 
If you don't know the answer, just say that you don't know, don't try to make up an answer.

{context}"""

user_info = """This is what we know about the user, and you can use this information to better tune your research:
Age: {age}
Gender: {gender}"""

template_suffix= """Question: {question}
Your response:"""

user_info = user_info.format(age = 18, gender = 'female')

COMBINED_PROMPT = template_prefix +'\n'+ user_info +'\n'+ template_suffix
print(COMBINED_PROMPT)

You are a movie recommender system that help users to find movies that match their preferences.
Use the following pieces of context to answer the question at the end.
If you don't know the answer, just say that you don't know, don't try to make up an answer.

{context}
This is what we know about the user, and you can use this information to better tune your research:
Age: 18
Gender: female
Question: {question}
Your response:

In [257]:
PROMPT = PromptTemplate(
    template=COMBINED_PROMPT, input_variables=["context", "question"])

chain_type_kwargs = {"prompt": PROMPT}
qa = RetrievalQA.from_chain_type(llm=OpenAI(), 
    chain_type="stuff", 
    retriever=docsearch.as_retriever(),
    return_source_documents=True, 
    chain_type_kwargs=chain_type_kwargs)

query = "Can you suggest me some action movie?"
result = qa({'query':query})
result['result']

' Sure, I can suggest some action movies for you. Here are a few examples: A Good Day to Die Hard, Goldfinger, Ong Bak 2, and The Raid 2. All of these movies have high ratings and feature thrilling action elements. I hope you find something that you enjoy!'

In [258]:
result['source_documents']

[Document(page_content='Title: A Good Day to Die Hard. Overview: Iconoclastic, take-no-prisoners cop John McClane, finds himself for the first time on foreign soil after traveling to Moscow to help his wayward son Jack - unaware that Jack is really a highly-trained CIA operative out to stop a nuclear weapons heist. With the Russian underworld in pursuit, and battling a countdown to war, the two McClanes discover that their opposing methods make them unstoppable heroes. Genres: Action, Thriller. Rating: 5.178041993422717', metadata={'genres': array(['Action', 'Thriller'], dtype=object), 'title': 'A Good Day to Die Hard', 'overview': 'Iconoclastic, take-no-prisoners cop John McClane, finds himself for the first time on foreign soil after traveling to Moscow to help his wayward son Jack - unaware that Jack is really a highly-trained CIA operative out to stop a nuclear weapons heist. With the Russian underworld in pursuit, and battling a countdown to war, the two McClanes discover that their opposing methods make them unstoppable heroes.', 'weighted_rate': 5.178041993422717, 'n_tokens': 111, 'vector': array([-0.01498934, -0.02228908, -0.01306022, ..., -0.00130485,
        -0.00664774, -0.0015233 ], dtype=float32), '_distance': 0.4059504568576813}),
 Document(page_content="Title: Goldfinger. Overview: Special agent 007 (Sean Connery) comes face to face with one of the most notorious villains of all time, and now he must outwit and outgun the powerful tycoon to prevent him from cashing in on a devious scheme to raid Fort Knox -- and obliterate the world's economy. Genres: Adventure, Action, Thriller. Rating: 6.536483669214732", metadata={'genres': array(['Adventure', 'Action', 'Thriller'], dtype=object), 'title': 'Goldfinger', 'overview': "Special agent 007 (Sean Connery) comes face to face with one of the most notorious villains of all time, and now he must outwit and outgun the powerful tycoon to prevent him from cashing in on a devious scheme to raid Fort Knox -- and obliterate the world's economy.", 'weighted_rate': 6.536483669214732, 'n_tokens': 89, 'vector': array([-0.01302788, -0.03417065, -0.00966397, ..., -0.01510197,
        -0.01324826, -0.00648477], dtype=float32), '_distance': 0.4087887406349182}),
 Document(page_content='Title: Ong Bak 2. Overview: Moments from death a young man is rescued by a renowned warrior. Realizing unsurpassed physical potential in the young boy he trains him into the most dangerous man alive. As he becomes a young man he goes on a lone mission of vengeance against the vicious slave traders who enslaved him as a youth and the treacherous warlord who killed his father. Genres: Adventure, Action, Thriller. Rating: 5.237966101694916', metadata={'genres': array(['Adventure', 'Action', 'Thriller'], dtype=object), 'title': 'Ong Bak 2', 'overview': 'Moments from death a young man is rescued by a renowned warrior. Realizing unsurpassed physical potential in the young boy he trains him into the most dangerous man alive. As he becomes a young man he goes on a lone mission of vengeance against the vicious slave traders who enslaved him as a youth and the treacherous warlord who killed his father.', 'weighted_rate': 5.237966101694916, 'n_tokens': 100, 'vector': array([-0.01203564, -0.02915789, -0.02014618, ..., -0.01302359,
        -0.00216949,  0.01389806], dtype=float32), '_distance': 0.41181957721710205}),
 Document(page_content='Title: The Raid 2. Overview: After fighting his way through an apartment building populated by an army of dangerous criminals and escaping with his life, SWAT team member Rama goes undercover, joining a powerful Indonesian crime syndicate to protect his family and uncover corrupt members of his own force. Genres: Action, Crime, Thriller. Rating: 6.7086887835703', metadata={'genres': array(['Action', 'Crime', 'Thriller'], dtype=object), 'title': 'The Raid 2', 'overview': 'After fighting his way through an apartment building populated by an army of dangerous criminals and escaping with his life, SWAT team member Rama goes undercover, joining a powerful Indonesian crime syndicate to protect his family and uncover corrupt members of his own force.', 'weighted_rate': 6.7086887835703, 'n_tokens': 78, 'vector': array([ 0.00455619, -0.02637059, -0.0112055 , ..., -0.02318425,
        -0.00706593,  0.01398521], dtype=float32), '_distance': 0.4204312264919281})]

## Content based

In [260]:
import pandas as pd

data = {
    "username": ["Alice", "Bob"],
    "age": [25, 32],
    "gender": ["F", "M"],
    "movies": [
        [("Transformers: The Last Knight", 7), ("PokÃ©mon: Spell of the Unknown", 5)],
        [("Bon Cop Bad Cop 2", 8), ("Goon: Last of the Enforcers", 9)]
    ]
}

# Convert the "movies" column into dictionaries
for i, row_movies in enumerate(data["movies"]):
    movie_dict = {}
    for movie, rating in row_movies:
        movie_dict[movie] = rating
    data["movies"][i] = movie_dict

# Create a pandas DataFrame
df = pd.DataFrame(data)

df.head()

  username  age gender                                             movies
0    Alice   25      F  {'Transformers: The Last Knight': 7, 'PokÃ©mon:...
1      Bob   32      M  {'Bon Cop Bad Cop 2': 8, 'Goon: Last of the En...

In [261]:
template_prefix = """You are a movie recommender system that help users to find movies that match their preferences. 
Use the following pieces of context to answer the question at the end. 
If you don't know the answer, just say that you don't know, don't try to make up an answer.

{context}"""

user_info = """This is what we know about the user, and you can use this information to better tune your research:
Age: {age}
Gender: {gender}
Movies already seen alongside with rating: {movies}"""

template_suffix= """Question: {question}
Your response:"""

In [262]:
age = df.loc[df['username']=='Alice']['age'][0]
gender = df.loc[df['username']=='Alice']['gender'][0]

movies = ''
# Iterate over the dictionary and output movie name and rating
for movie, rating in df['movies'][0].items():
    output_string = f"Movie: {movie}, Rating: {rating}" + "\n"
    movies+=output_string
    #print(output_string)
user_info = user_info.format(age = age, gender = gender, movies = movies)

COMBINED_PROMPT = template_prefix +'\n'+ user_info +'\n'+ template_suffix
print(COMBINED_PROMPT)

You are a movie recommender system that help users to find movies that match their preferences.
Use the following pieces of context to answer the question at the end.
If you don't know the answer, just say that you don't know, don't try to make up an answer.

{context}
This is what we know about the user, and you can use this information to better tune your research:
Age: 25
Gender: F
Movies already seen alongside with rating: Movie: Transformers: The Last Knight, Rating: 7
Movie: PokÃ©mon: Spell of the Unknown, Rating: 5

Question: {question}
Your response:

In [263]:
PROMPT = PromptTemplate(
    template=COMBINED_PROMPT, input_variables=["context", "question"])

chain_type_kwargs = {"prompt": PROMPT}
qa = RetrievalQA.from_chain_type(llm=OpenAI(), 
    chain_type="stuff", 
    retriever=docsearch.as_retriever(),
    return_source_documents=True, 
    chain_type_kwargs=chain_type_kwargs)

query = "Can you suggest me some action movie based on my background?"
result = qa({'query':query})
result['result']

" Based on your age, gender, and the movies you've already seen, I would suggest the following action movies: The Raid 2 (Action, Crime, Thriller; Rating: 6.71), Ong Bak 2 (Adventure, Action, Thriller; Rating: 5.24), Hitman: Agent 47 (Action, Crime, Thriller; Rating: 5.37), and Kingsman: The Secret Service (Crime, Comedy, Action, Adventure; Rating: 7.43)."

In [264]:
result['source_documents']

[Document(page_content='Title: The Raid 2. Overview: After fighting his way through an apartment building populated by an army of dangerous criminals and escaping with his life, SWAT team member Rama goes undercover, joining a powerful Indonesian crime syndicate to protect his family and uncover corrupt members of his own force. Genres: Action, Crime, Thriller. Rating: 6.7086887835703', metadata={'genres': array(['Action', 'Crime', 'Thriller'], dtype=object), 'title': 'The Raid 2', 'overview': 'After fighting his way through an apartment building populated by an army of dangerous criminals and escaping with his life, SWAT team member Rama goes undercover, joining a powerful Indonesian crime syndicate to protect his family and uncover corrupt members of his own force.', 'weighted_rate': 6.7086887835703, 'n_tokens': 78, 'vector': array([ 0.00455619, -0.02637059, -0.0112055 , ..., -0.02318425,
        -0.00706593,  0.01398521], dtype=float32), '_distance': 0.4141116142272949}),
 Document(page_content='Title: Ong Bak 2. Overview: Moments from death a young man is rescued by a renowned warrior. Realizing unsurpassed physical potential in the young boy he trains him into the most dangerous man alive. As he becomes a young man he goes on a lone mission of vengeance against the vicious slave traders who enslaved him as a youth and the treacherous warlord who killed his father. Genres: Adventure, Action, Thriller. Rating: 5.237966101694916', metadata={'genres': array(['Adventure', 'Action', 'Thriller'], dtype=object), 'title': 'Ong Bak 2', 'overview': 'Moments from death a young man is rescued by a renowned warrior. Realizing unsurpassed physical potential in the young boy he trains him into the most dangerous man alive. As he becomes a young man he goes on a lone mission of vengeance against the vicious slave traders who enslaved him as a youth and the treacherous warlord who killed his father.', 'weighted_rate': 5.237966101694916, 'n_tokens': 100, 'vector': array([-0.01203564, -0.02915789, -0.02014618, ..., -0.01302359,
        -0.00216949,  0.01389806], dtype=float32), '_distance': 0.41482454538345337}),
 Document(page_content='Title: Hitman: Agent 47. Overview: An assassin teams up with a woman to help her find her father and uncover the mysteries of her ancestry. Genres: Action, Crime, Thriller. Rating: 5.365800865800866', metadata={'genres': array(['Action', 'Crime', 'Thriller'], dtype=object), 'title': 'Hitman: Agent 47', 'overview': 'An assassin teams up with a woman to help her find her father and uncover the mysteries of her ancestry.', 'weighted_rate': 5.365800865800866, 'n_tokens': 52, 'vector': array([-0.00566491, -0.01658553, -0.02255735, ..., -0.01242317,
        -0.01303058, -0.00709073], dtype=float32), '_distance': 0.42523619532585144}),
 Document(page_content="Title: Kingsman: The Secret Service. Overview: The story of a super-secret spy organization that recruits an unrefined but promising street kid into the agency's ultra-competitive training program just as a global threat emerges from a twisted tech genius. Genres: Crime, Comedy, Action, Adventure. Rating: 7.4264800861141005", metadata={'genres': array(['Crime', 'Comedy', 'Action', 'Adventure'], dtype=object), 'title': 'Kingsman: The Secret Service', 'overview': "The story of a super-secret spy organization that recruits an unrefined but promising street kid into the agency's ultra-competitive training program just as a global threat emerges from a twisted tech genius.", 'weighted_rate': 7.4264800861141005, 'n_tokens': 72, 'vector': array([-0.00744663, -0.02387108, -0.00821877, ..., -0.01711808,
        -0.03188046,  0.00557843], dtype=float32), '_distance': 0.4267725646495819})]

In [ ]:
# imports
import pandas as pd
import tiktoken
import os
import openai

openai.api_key = os.environ["OPENAI_API_KEY"]

from openai.embeddings_utils import get_embedding